compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
gpu_ids: "0,1"
machine_rank: 0
main_process_ip: "localhost"
main_process_port: 29500
main_training_function: main
mixed_precision: "no"
num_machines: 1
num_processes: 2
use_cpu: false